services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
    depends_on:
      - gateway

  todo_service:
    container_name: todo_service
    build:
      context: ./todo_service
      dockerfile: Dockerfile
      target: dev
    ports:
      - 8080:8080
    volumes:
      - ./:/app:delegated
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: todo
      DB_PASSWORD: todo
      DB_NAME: todo_db
      DB_SSL_MODE: disable
    working_dir: /app/todo_service
    command:
      - go
      - run
      - main.go
    depends_on:
      db:
        condition: service_healthy

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
      target: dev
    tty: true
    stdin_open: true
    ports:
      - 2000:2000
    volumes:
      - ./:/app:delegated
    working_dir: /app/gateway
    command:
      - go
      - run
      - main.go
    depends_on:
      - todo_service
    # - user_service

  db:
    container_name: db
    image: postgres:16.1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./.docker/db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 3s
      timeout: 5s
      retries: 60

  user_service:
    container_name: user_service
    build:
      context: ./user_service
      dockerfile: Dockerfile
      target: dev
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 3002:3002
    volumes:
      - ./:/app:delegated
    working_dir: /app/user_service
    command:
      - go
      - run
      - main.go
    depends_on:
      db:
        condition: service_healthy
      # redis:
      #   condition: service_healthy

  # redis:
  #   container_name: redis
  #   image: redis:7.2.3
  #   environment:
  #     ALLOW_EMPTY_PASSWORD: yes
  #   ports:
  #     - 6379:6379
  #   healthcheck:
  #     test:
  #       - CMD
  #       - redis-cli
  #       - ping

volumes:
  db_data:
    driver: local
