name: Gateway Test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'gateway/**/*.go'
      - 'gateway/**/go.*'
      - 'gen/go/todo/*.go'

jobs:
  gateway:
    name: Gateway
    uses: './.github/workflows/reusable_ci.yaml'
    with:
      root: 'gateway'
