name: Gateway Test

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - 'gateway/**/*.go'
      - 'gateway/**/go.*'
      - 'gen/go/todo/*.go'

jobs:
  gateway:
    name: Gateway
    uses: './.github/workflows/reusable_ci.yaml'
    with:
      root: 'gateway'
