// Code generated by "enumer -type=TodoStatus -text -json -transform=snake-upper"; DO NOT EDIT.

package model

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _TodoStatusName = "TODO_STATUS_UNSPECIFIEDTODO_STATUS_DOINGTODO_STATUS_DONE"

var _TodoStatusIndex = [...]uint8{0, 23, 40, 56}

const _TodoStatusLowerName = "todo_status_unspecifiedtodo_status_doingtodo_status_done"

func (i TodoStatus) String() string {
	if i >= TodoStatus(len(_TodoStatusIndex)-1) {
		return fmt.Sprintf("TodoStatus(%d)", i)
	}
	return _TodoStatusName[_TodoStatusIndex[i]:_TodoStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TodoStatusNoOp() {
	var x [1]struct{}
	_ = x[TodoStatusUnspecified-(0)]
	_ = x[TodoStatusDoing-(1)]
	_ = x[TodoStatusDone-(2)]
}

var _TodoStatusValues = []TodoStatus{TodoStatusUnspecified, TodoStatusDoing, TodoStatusDone}

var _TodoStatusNameToValueMap = map[string]TodoStatus{
	_TodoStatusName[0:23]:       TodoStatusUnspecified,
	_TodoStatusLowerName[0:23]:  TodoStatusUnspecified,
	_TodoStatusName[23:40]:      TodoStatusDoing,
	_TodoStatusLowerName[23:40]: TodoStatusDoing,
	_TodoStatusName[40:56]:      TodoStatusDone,
	_TodoStatusLowerName[40:56]: TodoStatusDone,
}

var _TodoStatusNames = []string{
	_TodoStatusName[0:23],
	_TodoStatusName[23:40],
	_TodoStatusName[40:56],
}

// TodoStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TodoStatusString(s string) (TodoStatus, error) {
	if val, ok := _TodoStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TodoStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TodoStatus values", s)
}

// TodoStatusValues returns all values of the enum
func TodoStatusValues() []TodoStatus {
	return _TodoStatusValues
}

// TodoStatusStrings returns a slice of all String values of the enum
func TodoStatusStrings() []string {
	strs := make([]string, len(_TodoStatusNames))
	copy(strs, _TodoStatusNames)
	return strs
}

// IsATodoStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TodoStatus) IsATodoStatus() bool {
	for _, v := range _TodoStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for TodoStatus
func (i TodoStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for TodoStatus
func (i *TodoStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("TodoStatus should be a string, got %s", data)
	}

	var err error
	*i, err = TodoStatusString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for TodoStatus
func (i TodoStatus) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for TodoStatus
func (i *TodoStatus) UnmarshalText(text []byte) error {
	var err error
	*i, err = TodoStatusString(string(text))
	return err
}
